#dataset: "NYU" # "kitti", "kitti_360"
# dataset: "kitti_360"
dataset: "kitti"

n_relations: 4

enable_log: false
# kitti_root: '/path/to/semantic_kitti'
kitti_root: '/root/dev/data/dataset/SemanticKITTI'
# kitti_preprocess_root: '/path/to/kitti/preprocess/folder'
kitti_preprocess_root: '/root/dev/data/dataset/SemanticKITTI/preprocess_cw'
kitti_logdir: '/path/to/semantic_kitti/logdir'

NYU_root: '/root/data/NYU_dataset/depthbin'
NYU_preprocess_root: '/root/data/NYU_dataset/preprocess/base'
logdir: '/root/dev/Modified_Monoscene/logdir'


fp_loss: true 
frustum_size: 8 
batch_size: 4
n_gpus: 4
num_workers_per_gpu: 12 # n4 have 128 workers
exp_prefix: "evt_3onoff_woNorm"
run: 1
lr: 1e-4
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: true
project_1_4: true
project_1_8: true